name: Build Python Application

description: |
  This composite action will build a Python project using pip or other tools.

inputs:
  version:
    description: 'Python version to use'
    required: true
    default: '3.8'

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.version }}
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run tests
      run: |
        pytest
