# repo-1/.github/workflows/unified-build-deployment.yaml
name: Unified Build & Deployment

on:
  workflow_call:
    inputs:
      language:
        required: true
        type: string
      env:
        required: true
        type: string
      upload_artifact:
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_name: ${{ steps.set-name.outputs.artifact_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set artifact name
        id: set-name
        run: echo "artifact_name=myapp-${{ inputs.language }}-${{ inputs.env }}" >> $GITHUB_OUTPUT

      - name: Build Java
        if: ${{ inputs.language == 'java' }}
        uses: ./build-java

      - name: Build Python
        if: ${{ inputs.language == 'python' }}
        uses: ./build-python

      - name: Upload Artifact
        if: ${{ inputs.upload_artifact }}
        uses: ./upload-artifact
        with:
          name: ${{ steps.set-name.outputs.artifact_name }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.env }}
      url: https://myapp-${{ inputs.env }}.example.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Java
        if: ${{ inputs.language == 'java' }}
        uses: ./deploy-java
        with:
          environment: ${{ inputs.env }}

      - name: Deploy Python
        if: ${{ inputs.language == 'python' }}
        uses: ./deploy-python
        with:
          environment: ${{ inputs.env }}

   
